name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging
      - 'feature/**'
  pull_request:
    branches:
      - main
      - staging
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
        node-version-file: .nvmrc

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: npm ci

      # 4️⃣ Run ESLint
      - name: Lint
        run: npm run lint

      # 5️⃣ Run TypeScript typecheck
      - name: Typecheck
        run: npm run typecheck

      # 6️⃣ Run tests (if you have any)
      - name: Tests
        run: npm test

      # 7️⃣ Optional: Copilot suggestion reminder
      - name: AI Review Reminder
        run: echo "Use GitHub Copilot in VS Code to review code locally before merging. Copilot will suggest fixes, refactors, and improvements."
