name: CI Pipeline

on:
  push:
    branches:
      - main
      - staging
      - 'feature/**'
  pull_request:
    branches:
      - main
      - staging
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run ESLint
      - name: Lint
        run: npm run lint

      # Run TypeScript typecheck
      - name: Typecheck
        run: npm run typecheck

      # Run tests 
      - name: Tests
        run: npm test

      # Trigger Vercel deployment on main or staging branches
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v22
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          prod: ${{ github.ref_name == 'main' }}

      # Copilot suggestion reminder
      - name: AI Review Reminder
        run: echo "Use GitHub Copilot in VS Code to review code locally before merging. Copilot will suggest fixes, refactors, and improvements."
